apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-spring
spec:
  containers:
    - name: kubernetes-spring
      image: rafasantos/kubernetes-spring
      imagePullPolicy: Never
#      env:
#      - name: HELLO_PUBLIC_MESSAGE
#        value: 'My public message from environment variables'
